# See: https://gohugo.io/getting-started/configuration/#merge-configuration-from-themes
_merge = "deep"

favicon_mstilecolor = "#2b5797"

### BGN: Structured Data ###
  description = "YourOnly.One ğŸ” Pages"
  keywords = ["YourOnlyOne", "YourOnly.One", "Yahuhanan Yukiya Sese Cuneta", "Yuki", "YoHan", "Yo-Han", "×™×”×•×—× ×Ÿ", "áœŒáœ“áœƒáœ’", "ì‚¬ìš”í•œ", "è¬é›ªçŸ¢ï¼ˆã‚†ãã‚„ï¼‰", "ìŠ¤ë…¸", "Seu-No", "SeuNo", "Snow", "Yohanan", "áœŒáœ“áœ‘áœˆáœˆáœ”", "áœŒáœ“áœ‘áœˆáœˆáœ•", "áœŒáœ‘áœ“áœ‘áœˆáœˆáœ”", "áœŒáœ‘áœ“áœ‘áœˆáœˆáœ•"] # Can be overriden per page
  images = ["https://rsc.youronly.one/img/y/Yuki_flag-300h.webp", "https://rsc.youronly.one/img/y/Yuki_flag-square-300x.webp"]
### END: Structured Data ###

### BGN: Theme Settings ###
  #disqus = "" # disqus account name
  #extraHead = "<script src="xxxx.js"></script>"
  #extraCSSFiles = ["css/foo.css", "css/bar.css"]
  mainSections = ["pages"]

  ## In a post's front matter, include a keyword images with a value of a list of URLs of images that will be used for Twitter Cards.
  twitterCards = true

  ## Insert content on every post
  #postHeaderContent = ""
  #postFooterContent = "<br/><br/><p>Subscribeï¼š<a target='_blank' href='https://mailchi.mp/a1a0d59e7a19/joway'>Joway's Blog</a></p>"

  [[socials]]
  name = "Â«HubÂ»"
  link = "https://im.youronly.one/"

  [[socials]]
  #name = "Â« The YOOki (æŸ³ç´€ ãƒ» ìœ  ê¸°) Chronicles Â»"
  name = "Â«YOOki Chronicles ğŸ“œÂ»"
  link = "https://im.youronly.one/yuki/"

  [[socials]]
  name = "Â«Snoworld â„ï¸Â»"
  link = "https://im.youronly.one/snoworld/"

  [[socials]]
  name = "Â«One Way Faith ğŸ›Â»"
  link = "https://im.youronly.one/way/"

  [[socials]]
  name = "Â«techmagus ğŸš€Â»"
  link = "https://im.youronly.one/techmagus/"

  [[socials]]
  name = "Â«Love ğŸ’Â»"
  link = "https://im.youronly.one/love/"
### END: Theme Settings ###

### BGN: Other Settings ###
  [semweb]
    datecreated = "2003-12-12"
    sameas = [
      "https://c.im/@YourOnlyOne",
      "https://pixelfed.social/YourOnlyOne",
      "https://www.youtube.com/@YourOnlyOneOfcl",
      "https://www.facebook.com/YourOnly.ONE.ofcl"
    ]
### END: Other Settings ###
